//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMiCay
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHD
    {
        public string MaHD { get; set; }
        public string MaMon { get; set; }
        public Nullable<int> SoLuongMon { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual Mon Mon { get; set; }
    }
}
