//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMiCay
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mon()
        {
            this.CTHD = new HashSet<CTHD>();
        }
    
        public string MaMon { get; set; }
        public string TenMon { get; set; }
        public decimal GiaCa { get; set; }
        public string AnhMon { get; set; }
        public string MaTheLoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHD { get; set; }
        public virtual LoaiMon LoaiMon { get; set; }
    }
}
