//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMiCay
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguyenLieu
    {
        public string MaNguyenLieu { get; set; }
        public string TenNguyenLieu { get; set; }
        public decimal GiaNguyenLieu { get; set; }
        public string DonVi { get; set; }
    }
}
