//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMiCay
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyQuanMiCayEntities : DbContext
    {
        public QuanLyQuanMiCayEntities()
            : base("name=QuanLyQuanMiCayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTHD> CTHD { get; set; }
        public virtual DbSet<HoaDon> HoaDon { get; set; }
        public virtual DbSet<KhachHang> KhachHang { get; set; }
        public virtual DbSet<LichDat> LichDat { get; set; }
        public virtual DbSet<LoaiMon> LoaiMon { get; set; }
        public virtual DbSet<Mon> Mon { get; set; }
        public virtual DbSet<NguyenLieu> NguyenLieu { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCap { get; set; }
        public virtual DbSet<NhanVien> NhanVien { get; set; }
        public virtual DbSet<PhanHoi> PhanHoi { get; set; }
        public virtual DbSet<TaiKhoanKhach> TaiKhoanKhach { get; set; }
        public virtual DbSet<TaiKhoanNhanVien> TaiKhoanNhanVien { get; set; }
        public virtual DbSet<VaiTro> VaiTro { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TongDoanhThuTheoThang> TongDoanhThuTheoThang { get; set; }
    
        public virtual int sp_InsertKhachHang(string tenKH, string sDT, Nullable<System.DateTime> ngaySinh, string diaChi, string gioiTinh, string tenTaiKhoanKhach, string matKhauKhach)
        {
            var tenKHParameter = tenKH != null ?
                new ObjectParameter("TenKH", tenKH) :
                new ObjectParameter("TenKH", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var tenTaiKhoanKhachParameter = tenTaiKhoanKhach != null ?
                new ObjectParameter("TenTaiKhoanKhach", tenTaiKhoanKhach) :
                new ObjectParameter("TenTaiKhoanKhach", typeof(string));
    
            var matKhauKhachParameter = matKhauKhach != null ?
                new ObjectParameter("MatKhauKhach", matKhauKhach) :
                new ObjectParameter("MatKhauKhach", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertKhachHang", tenKHParameter, sDTParameter, ngaySinhParameter, diaChiParameter, gioiTinhParameter, tenTaiKhoanKhachParameter, matKhauKhachParameter);
        }
    
        public virtual int sp_InsertLichDat(Nullable<System.DateTime> ngayDat, Nullable<System.TimeSpan> gioDat, Nullable<byte> soBan, string maKH)
        {
            var ngayDatParameter = ngayDat.HasValue ?
                new ObjectParameter("NgayDat", ngayDat) :
                new ObjectParameter("NgayDat", typeof(System.DateTime));
    
            var gioDatParameter = gioDat.HasValue ?
                new ObjectParameter("GioDat", gioDat) :
                new ObjectParameter("GioDat", typeof(System.TimeSpan));
    
            var soBanParameter = soBan.HasValue ?
                new ObjectParameter("SoBan", soBan) :
                new ObjectParameter("SoBan", typeof(byte));
    
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertLichDat", ngayDatParameter, gioDatParameter, soBanParameter, maKHParameter);
        }
    
        public virtual int sp_InsertMon(string tenMon, Nullable<decimal> giaCa, string anhMon, string maTheLoai)
        {
            var tenMonParameter = tenMon != null ?
                new ObjectParameter("TenMon", tenMon) :
                new ObjectParameter("TenMon", typeof(string));
    
            var giaCaParameter = giaCa.HasValue ?
                new ObjectParameter("GiaCa", giaCa) :
                new ObjectParameter("GiaCa", typeof(decimal));
    
            var anhMonParameter = anhMon != null ?
                new ObjectParameter("AnhMon", anhMon) :
                new ObjectParameter("AnhMon", typeof(string));
    
            var maTheLoaiParameter = maTheLoai != null ?
                new ObjectParameter("MaTheLoai", maTheLoai) :
                new ObjectParameter("MaTheLoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertMon", tenMonParameter, giaCaParameter, anhMonParameter, maTheLoaiParameter);
        }
    
        public virtual int sp_InsertNguyenLieu(string tenNguyenLieu, Nullable<decimal> giaNguyenLieu, string donVi)
        {
            var tenNguyenLieuParameter = tenNguyenLieu != null ?
                new ObjectParameter("TenNguyenLieu", tenNguyenLieu) :
                new ObjectParameter("TenNguyenLieu", typeof(string));
    
            var giaNguyenLieuParameter = giaNguyenLieu.HasValue ?
                new ObjectParameter("GiaNguyenLieu", giaNguyenLieu) :
                new ObjectParameter("GiaNguyenLieu", typeof(decimal));
    
            var donViParameter = donVi != null ?
                new ObjectParameter("DonVi", donVi) :
                new ObjectParameter("DonVi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertNguyenLieu", tenNguyenLieuParameter, giaNguyenLieuParameter, donViParameter);
        }
    
        public virtual int sp_InsertNhaCC(string tenNCC, string sDTNCC, string diaChiNCC)
        {
            var tenNCCParameter = tenNCC != null ?
                new ObjectParameter("TenNCC", tenNCC) :
                new ObjectParameter("TenNCC", typeof(string));
    
            var sDTNCCParameter = sDTNCC != null ?
                new ObjectParameter("SDTNCC", sDTNCC) :
                new ObjectParameter("SDTNCC", typeof(string));
    
            var diaChiNCCParameter = diaChiNCC != null ?
                new ObjectParameter("DiaChiNCC", diaChiNCC) :
                new ObjectParameter("DiaChiNCC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertNhaCC", tenNCCParameter, sDTNCCParameter, diaChiNCCParameter);
        }
    
        public virtual int sp_InsertNhanVien(string tenNV, string sDTNV, Nullable<System.DateTime> ngaySinh, string diaChi, string gioiTinh, string tenTaiKhoanNV, string matKhau)
        {
            var tenNVParameter = tenNV != null ?
                new ObjectParameter("TenNV", tenNV) :
                new ObjectParameter("TenNV", typeof(string));
    
            var sDTNVParameter = sDTNV != null ?
                new ObjectParameter("SDTNV", sDTNV) :
                new ObjectParameter("SDTNV", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var tenTaiKhoanNVParameter = tenTaiKhoanNV != null ?
                new ObjectParameter("TenTaiKhoanNV", tenTaiKhoanNV) :
                new ObjectParameter("TenTaiKhoanNV", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertNhanVien", tenNVParameter, sDTNVParameter, ngaySinhParameter, diaChiParameter, gioiTinhParameter, tenTaiKhoanNVParameter, matKhauParameter);
        }
    
        public virtual int sp_InsertOrder(string maKH, Nullable<decimal> tongGia)
        {
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            var tongGiaParameter = tongGia.HasValue ?
                new ObjectParameter("TongGia", tongGia) :
                new ObjectParameter("TongGia", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertOrder", maKHParameter, tongGiaParameter);
        }
    
        public virtual int sp_InsertPhanHoi(string noiDungPhanHoi, string maKH)
        {
            var noiDungPhanHoiParameter = noiDungPhanHoi != null ?
                new ObjectParameter("NoiDungPhanHoi", noiDungPhanHoi) :
                new ObjectParameter("NoiDungPhanHoi", typeof(string));
    
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertPhanHoi", noiDungPhanHoiParameter, maKHParameter);
        }
    }
}
