//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMiCay
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoanNhanVien
    {
        public string MaTaiKhoanNV { get; set; }
        public string TenTaiKhoanNV { get; set; }
        public string MatKhau { get; set; }
        public System.DateTime NgayTao { get; set; }
        public string MaNV { get; set; }
        public string MaVaiTro { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual VaiTro VaiTro { get; set; }
    }
}
