//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMiCay
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoanKhach
    {
        public string MaTaiKhoanKhach { get; set; }
        public string TenTaiKhoanKhach { get; set; }
        public string MatKhauKhach { get; set; }
        public System.DateTime NgayTao { get; set; }
        public string MaKH { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
